### ISSUE TITLE
Large Nanite Meshes

### ISSUE THREAD

**Issue by atemnyakov** [VoxelPlugin/VoxelCore#1]
I encountered an issue with large Nanite meshes when creating them using FVoxelNaniteBuilder. Then don't render correctly and it takes a lot of time to do it. I noticed that there was a check for the data size. Such meshes trigger it. I read the UE5 source code and noticed it kind of split large meshes into parts. And that is why they could work fine. Does VoxelCore support such meshes? If not, are there any plans to add support for them? Thank you in advance for your answers.

**Comment by Phyronnaz** [comment]
Hi there!

Large meshes are currently not supported - they might be in the future.
