### ISSUE TITLE
Whether the Nanite generated at runtime needs to be serialized to the disk or not？

### ISSUE THREAD

**Issue by whucj** [VoxelPlugin/VoxelCore#3]
Thank you very much for your work. I looked at the UE source code and compared it with yours. The Nanite generated under Editor needs to be serialized to the disk. Then, for the Nanite generated at runtime, is it necessary to serialize it to the disk?

**Comment by Phyronnaz** [comment]
@whucj it is not - we store the mesh into Nanite root pages which are never streamed out
